-- AlterTable
ALTER TABLE "Card" ADD COLUMN     "easiness" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
ADD COLUMN     "interval" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "nextReview" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "reps" INTEGER NOT NULL DEFAULT 0;
